"""empty message

Revision ID: e7f6807c91e0
Revises: 6df45805b831
Create Date: 2018-01-14 04:23:46.039469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f6807c91e0'
down_revision = '6df45805b831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('Film_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'Film_id')
    # ### end Alembic commands ###
